// SPDX-License-Identifier: GPL-2.0

#include "internal/macro.h"

#include "unicode/atari.h"
#include "unicode/utf8.h"

static const struct {
	unicode_t code;
	const char *name;
} atari_st_charset[256] = {
	{ 0x00000, /* <NUL> */ "NULL" },
	{ 0x021e7, /* ⇧     */ "UPWARDS WHITE ARROW" },
	{ 0x021e9, /* ⇩     */ "DOWNWARDS WHITE ARROW" },
	{ 0x021e8, /* ⇨     */ "RIGHTWARDS WHITE ARROW" },
	{ 0x021e6, /* ⇦     */ "LEFTWARDS WHITE ARROW" },
	{ 0x1fbbd, /* 🮽     */ "NEGATIVE DIAGONAL CROSS" },
	{ 0x1fbbe, /* 🮾     */ "NEGATIVE DIAGONAL MIDDLE RIGHT TO LOWER CENTRE" },
	{ 0x1fbbf, /* 🮿     */ "NEGATIVE DIAGONAL DIAMOND" },
	{ 0x02713, /* ✓     */ "CHECK MARK" },
	{ 0x1f552, /* 🕒    */ "CLOCK FACE THREE OCLOCK" },
	{ 0x1f514, /* 🔔    */ "BELL" },
	{ 0x0266a, /* ♪     */ "EIGHTH NOTE" },
	{ 0x0240c, /* ␌     */ "SYMBOL FOR FORM FEED" },
	{ 0x0240d, /* ␍     */ "SYMBOL FOR CARRIAGE RETURN" },
	{ 0x0000e, /* <SO>  */ "SHIFT OUT" },
	{ 0x0000f, /* <SI>  */ "SHIFT IN" },
	{ 0x1fbf0, /* 🯰     */ "SEGMENTED DIGIT ZERO" },
	{ 0x1fbf1, /* 🯱     */ "SEGMENTED DIGIT ONE" },
	{ 0x1fbf2, /* 🯲     */ "SEGMENTED DIGIT TWO" },
	{ 0x1fbf3, /* 🯳     */ "SEGMENTED DIGIT THREE" },
	{ 0x1fbf4, /* 🯴     */ "SEGMENTED DIGIT FOUR" },
	{ 0x1fbf5, /* 🯵     */ "SEGMENTED DIGIT FIVE" },
	{ 0x1fbf6, /* 🯶     */ "SEGMENTED DIGIT SIX" },
	{ 0x1fbf7, /* 🯷     */ "SEGMENTED DIGIT SEVEN" },
	{ 0x1fbf8, /* 🯸     */ "SEGMENTED DIGIT EIGHT" },
	{ 0x1fbf9, /* 🯹     */ "SEGMENTED DIGIT NINE" },
	{ 0x00259, /* ə     */ "LATIN SMALL LETTER SCHWA" },
	{ 0x0241b, /* ␛     */ "SYMBOL FOR ESCAPE" },
	{ 0x0001c, /* <FS>  */ "FILE SEPARATOR" },
	{ 0x0001d, /* <GS>  */ "GROUP SEPARATOR" },
	{ 0x0001e, /* <RS>  */ "RECORD SEPARATOR" },
	{ 0x0001f, /* <US>  */ "UNIT SEPARATOR" },
	{ 0x00020, /* <SP>  */ "SPACE" },
	{ 0x00021, /* !     */ "EXCLAMATION MARK" },
	{ 0x00022, /* "     */ "QUOTATION MARK" },
	{ 0x00023, /* #     */ "NUMBER SIGN" },
	{ 0x00024, /* $     */ "DOLLAR SIGN" },
	{ 0x00025, /* %     */ "PERCENT SIGN" },
	{ 0x00026, /* &     */ "AMPERSAND" },
	{ 0x00027, /* '     */ "APOSTROPHE" },
	{ 0x00028, /* (     */ "LEFT PARENTHESIS" },
	{ 0x00029, /* )     */ "RIGHT PARENTHESIS" },
	{ 0x0002a, /* *     */ "ASTERISK" },
	{ 0x0002b, /* +     */ "PLUS SIGN" },
	{ 0x0002c, /* ,     */ "COMMA" },
	{ 0x0002d, /* -     */ "HYPHEN-MINUS" },
	{ 0x0002e, /* .     */ "FULL STOP" },
	{ 0x0002f, /* /     */ "SOLIDUS" },
	{ 0x00030, /* 0     */ "DIGIT ZERO" },
	{ 0x00031, /* 1     */ "DIGIT ONE" },
	{ 0x00032, /* 2     */ "DIGIT TWO" },
	{ 0x00033, /* 3     */ "DIGIT THREE" },
	{ 0x00034, /* 4     */ "DIGIT FOUR" },
	{ 0x00035, /* 5     */ "DIGIT FIVE" },
	{ 0x00036, /* 6     */ "DIGIT SIX" },
	{ 0x00037, /* 7     */ "DIGIT SEVEN" },
	{ 0x00038, /* 8     */ "DIGIT EIGHT" },
	{ 0x00039, /* 9     */ "DIGIT NINE" },
	{ 0x0003a, /* :     */ "COLON" },
	{ 0x0003b, /* ;     */ "SEMICOLON" },
	{ 0x0003c, /* <     */ "LESS-THAN SIGN" },
	{ 0x0003d, /* =     */ "EQUALS SIGN" },
	{ 0x0003e, /* >     */ "GREATER-THAN SIGN" },
	{ 0x0003f, /* ?     */ "QUESTION MARK" },
	{ 0x00040, /* @     */ "COMMERCIAL AT" },
	{ 0x00041, /* A     */ "LATIN CAPITAL LETTER A" },
	{ 0x00042, /* B     */ "LATIN CAPITAL LETTER B" },
	{ 0x00043, /* C     */ "LATIN CAPITAL LETTER C" },
	{ 0x00044, /* D     */ "LATIN CAPITAL LETTER D" },
	{ 0x00045, /* E     */ "LATIN CAPITAL LETTER E" },
	{ 0x00046, /* F     */ "LATIN CAPITAL LETTER F" },
	{ 0x00047, /* G     */ "LATIN CAPITAL LETTER G" },
	{ 0x00048, /* H     */ "LATIN CAPITAL LETTER H" },
	{ 0x00049, /* I     */ "LATIN CAPITAL LETTER I" },
	{ 0x0004a, /* J     */ "LATIN CAPITAL LETTER J" },
	{ 0x0004b, /* K     */ "LATIN CAPITAL LETTER K" },
	{ 0x0004c, /* L     */ "LATIN CAPITAL LETTER L" },
	{ 0x0004d, /* M     */ "LATIN CAPITAL LETTER M" },
	{ 0x0004e, /* N     */ "LATIN CAPITAL LETTER N" },
	{ 0x0004f, /* O     */ "LATIN CAPITAL LETTER O" },
	{ 0x00050, /* P     */ "LATIN CAPITAL LETTER P" },
	{ 0x00051, /* Q     */ "LATIN CAPITAL LETTER Q" },
	{ 0x00052, /* R     */ "LATIN CAPITAL LETTER R" },
	{ 0x00053, /* S     */ "LATIN CAPITAL LETTER S" },
	{ 0x00054, /* T     */ "LATIN CAPITAL LETTER T" },
	{ 0x00055, /* U     */ "LATIN CAPITAL LETTER U" },
	{ 0x00056, /* V     */ "LATIN CAPITAL LETTER V" },
	{ 0x00057, /* W     */ "LATIN CAPITAL LETTER W" },
	{ 0x00058, /* X     */ "LATIN CAPITAL LETTER X" },
	{ 0x00059, /* Y     */ "LATIN CAPITAL LETTER Y" },
	{ 0x0005a, /* Z     */ "LATIN CAPITAL LETTER Z" },
	{ 0x0005b, /* [     */ "LEFT SQUARE BRACKET" },
	{ 0x0005c, /* \     */ "REVERSE SOLIDUS" },
	{ 0x0005d, /* ]     */ "RIGHT SQUARE BRACKET" },
	{ 0x0005e, /* ^     */ "CIRCUMFLEX ACCENT" },
	{ 0x0005f, /* _     */ "LOW LINE" },
	{ 0x00060, /* `     */ "GRAVE ACCENT" },
	{ 0x00061, /* a     */ "LATIN SMALL LETTER A" },
	{ 0x00062, /* b     */ "LATIN SMALL LETTER B" },
	{ 0x00063, /* c     */ "LATIN SMALL LETTER C" },
	{ 0x00064, /* d     */ "LATIN SMALL LETTER D" },
	{ 0x00065, /* e     */ "LATIN SMALL LETTER E" },
	{ 0x00066, /* f     */ "LATIN SMALL LETTER F" },
	{ 0x00067, /* g     */ "LATIN SMALL LETTER G" },
	{ 0x00068, /* h     */ "LATIN SMALL LETTER H" },
	{ 0x00069, /* i     */ "LATIN SMALL LETTER I" },
	{ 0x0006a, /* j     */ "LATIN SMALL LETTER J" },
	{ 0x0006b, /* k     */ "LATIN SMALL LETTER K" },
	{ 0x0006c, /* l     */ "LATIN SMALL LETTER L" },
	{ 0x0006d, /* m     */ "LATIN SMALL LETTER M" },
	{ 0x0006e, /* n     */ "LATIN SMALL LETTER N" },
	{ 0x0006f, /* o     */ "LATIN SMALL LETTER O" },
	{ 0x00070, /* p     */ "LATIN SMALL LETTER P" },
	{ 0x00071, /* q     */ "LATIN SMALL LETTER Q" },
	{ 0x00072, /* r     */ "LATIN SMALL LETTER R" },
	{ 0x00073, /* s     */ "LATIN SMALL LETTER S" },
	{ 0x00074, /* t     */ "LATIN SMALL LETTER T" },
	{ 0x00075, /* u     */ "LATIN SMALL LETTER U" },
	{ 0x00076, /* v     */ "LATIN SMALL LETTER V" },
	{ 0x00077, /* w     */ "LATIN SMALL LETTER W" },
	{ 0x00078, /* x     */ "LATIN SMALL LETTER X" },
	{ 0x00079, /* y     */ "LATIN SMALL LETTER Y" },
	{ 0x0007a, /* z     */ "LATIN SMALL LETTER Z" },
	{ 0x0007b, /* {     */ "LEFT CURLY BRACKET" },
	{ 0x0007c, /* |     */ "VERTICAL LINE" },
	{ 0x0007d, /* }     */ "RIGHT CURLY BRACKET" },
	{ 0x0007e, /* ~     */ "TILDE" },
	{ 0x0007f, /* <DEL> */ "DELETE" },
	{ 0x000c7, /* Ç     */ "LATIN CAPITAL LETTER C WITH CEDILLA" },
	{ 0x000fc, /* ü     */ "LATIN SMALL LETTER U WITH DIAERESIS" },
	{ 0x000e9, /* é     */ "LATIN SMALL LETTER E WITH ACUTE" },
	{ 0x000e2, /* â     */ "LATIN SMALL LETTER A WITH CIRCUMFLEX" },
	{ 0x000e4, /* ä     */ "LATIN SMALL LETTER A WITH DIAERESIS" },
	{ 0x000e0, /* à     */ "LATIN SMALL LETTER A WITH GRAVE" },
	{ 0x000e5, /* å     */ "LATIN SMALL LETTER A WITH RING ABOVE" },
	{ 0x000e7, /* ç     */ "LATIN SMALL LETTER C WITH CEDILLA" },
	{ 0x000ea, /* ê     */ "LATIN SMALL LETTER E WITH CIRCUMFLEX" },
	{ 0x000eb, /* ë     */ "LATIN SMALL LETTER E WITH DIAERESIS" },
	{ 0x000e8, /* è     */ "LATIN SMALL LETTER E WITH GRAVE" },
	{ 0x000ef, /* ï     */ "LATIN SMALL LETTER I WITH DIAERESIS" },
	{ 0x000ee, /* î     */ "LATIN SMALL LETTER I WITH CIRCUMFLEX" },
	{ 0x000ec, /* ì     */ "LATIN SMALL LETTER I WITH GRAVE" },
	{ 0x000c4, /* Ä     */ "LATIN CAPITAL LETTER A WITH DIAERESIS" },
	{ 0x000c5, /* Å     */ "LATIN CAPITAL LETTER A WITH RING ABOVE" },
	{ 0x000c9, /* É     */ "LATIN CAPITAL LETTER E WITH ACUTE" },
	{ 0x000e6, /* æ     */ "LATIN SMALL LETTER AE" },
	{ 0x000c6, /* Æ     */ "LATIN CAPITAL LETTER AE" },
	{ 0x000f4, /* ô     */ "LATIN SMALL LETTER O WITH CIRCUMFLEX" },
	{ 0x000f6, /* ö     */ "LATIN SMALL LETTER O WITH DIAERESIS" },
	{ 0x000f2, /* ò     */ "LATIN SMALL LETTER O WITH GRAVE" },
	{ 0x000fb, /* û     */ "LATIN SMALL LETTER U WITH CIRCUMFLEX" },
	{ 0x000f9, /* ù     */ "LATIN SMALL LETTER U WITH GRAVE" },
	{ 0x000ff, /* ÿ     */ "LATIN SMALL LETTER Y WITH DIAERESIS" },
	{ 0x000d6, /* Ö     */ "LATIN CAPITAL LETTER O WITH DIAERESIS" },
	{ 0x000dc, /* Ü     */ "LATIN CAPITAL LETTER U WITH DIAERESIS" },
	{ 0x000a2, /* ¢     */ "CENT SIGN" },
	{ 0x000a3, /* £     */ "POUND SIGN" },
	{ 0x000a5, /* ¥     */ "YEN SIGN" },
	{ 0x000df, /* ß     */ "LATIN SMALL LETTER SHARP S" },
	{ 0x00192, /* ƒ     */ "LATIN SMALL LETTER F WITH HOOK" },
	{ 0x000e1, /* á     */ "LATIN SMALL LETTER A WITH ACUTE" },
	{ 0x000ed, /* í     */ "LATIN SMALL LETTER I WITH ACUTE" },
	{ 0x000f3, /* ó     */ "LATIN SMALL LETTER O WITH ACUTE" },
	{ 0x000fa, /* ú     */ "LATIN SMALL LETTER U WITH ACUTE" },
	{ 0x000f1, /* ñ     */ "LATIN SMALL LETTER N WITH TILDE" },
	{ 0x000d1, /* Ñ     */ "LATIN CAPITAL LETTER N WITH TILDE" },
	{ 0x000aa, /* ª     */ "FEMININE ORDINAL INDICATOR" },
	{ 0x000ba, /* º     */ "MASCULINE ORDINAL INDICATOR" },
	{ 0x000bf, /* ¿     */ "INVERTED QUESTION MARK" },
	{ 0x02310, /* ⌐     */ "REVERSED NOT SIGN" },
	{ 0x000ac, /* ¬     */ "NOT SIGN" },
	{ 0x000bd, /* ½     */ "VULGAR FRACTION ONE HALF" },
	{ 0x000bc, /* ¼     */ "VULGAR FRACTION ONE QUARTER" },
	{ 0x000a1, /* ¡     */ "INVERTED EXCLAMATION MARK" },
	{ 0x000ab, /* «     */ "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK" },
	{ 0x000bb, /* »     */ "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK" },
	{ 0x000e3, /* ã     */ "LATIN SMALL LETTER A WITH TILDE" },
	{ 0x000f5, /* õ     */ "LATIN SMALL LETTER O WITH TILDE" },
	{ 0x000d8, /* Ø     */ "LATIN CAPITAL LETTER O WITH STROKE" },
	{ 0x000f8, /* ø     */ "LATIN SMALL LETTER O WITH STROKE" },
	{ 0x00153, /* œ     */ "LATIN SMALL LIGATURE OE" },
	{ 0x00152, /* Œ     */ "LATIN CAPITAL LIGATURE OE" },
	{ 0x000c0, /* À     */ "LATIN CAPITAL LETTER A WITH GRAVE" },
	{ 0x000c3, /* Ã     */ "LATIN CAPITAL LETTER A WITH TILDE" },
	{ 0x000d5, /* Õ     */ "LATIN CAPITAL LETTER O WITH TILDE" },
	{ 0x000a8, /* ¨     */ "DIAERESIS" },
	{ 0x000b4, /* ´     */ "ACUTE ACCENT" },
	{ 0x02020, /* †     */ "DAGGER" },
	{ 0x000b6, /* ¶     */ "PILCROW SIGN" },
	{ 0x000a9, /* ©     */ "COPYRIGHT SIGN" },
	{ 0x000ae, /* ®     */ "REGISTERED SIGN" },
	{ 0x02122, /* ™     */ "TRADE MARK SIGN" },
	{ 0x00133, /* ĳ     */ "LATIN SMALL LIGATURE IJ" },
	{ 0x00132, /* Ĳ     */ "LATIN CAPITAL LIGATURE IJ" },
	{ 0x005d0, /* א     */ "HEBREW LETTER ALEF" },
	{ 0x005d1, /* ב     */ "HEBREW LETTER BET" },
	{ 0x005d2, /* ג     */ "HEBREW LETTER GIMEL" },
	{ 0x005d3, /* ד     */ "HEBREW LETTER DALET" },
	{ 0x005d4, /* ה     */ "HEBREW LETTER HE" },
	{ 0x005d5, /* ו     */ "HEBREW LETTER VAV" },
	{ 0x005d6, /* ז     */ "HEBREW LETTER ZAYIN" },
	{ 0x005d7, /* ח     */ "HEBREW LETTER HET" },
	{ 0x005d8, /* ט     */ "HEBREW LETTER TET" },
	{ 0x005d9, /* י     */ "HEBREW LETTER YOD" },
	{ 0x005db, /* כ     */ "HEBREW LETTER KAF" },
	{ 0x005dc, /* ל     */ "HEBREW LETTER LAMED" },
	{ 0x005de, /* מ     */ "HEBREW LETTER MEM" },
	{ 0x005e0, /* נ     */ "HEBREW LETTER NUN" },
	{ 0x005e1, /* ס     */ "HEBREW LETTER SAMEKH" },
	{ 0x005e2, /* ע     */ "HEBREW LETTER AYIN" },
	{ 0x005e4, /* פ     */ "HEBREW LETTER PE" },
	{ 0x005e6, /* צ     */ "HEBREW LETTER TSADI" },
	{ 0x005e7, /* ק     */ "HEBREW LETTER QOF" },
	{ 0x005e8, /* ר     */ "HEBREW LETTER RESH" },
	{ 0x005e9, /* ש     */ "HEBREW LETTER SHIN" },
	{ 0x005ea, /* ת     */ "HEBREW LETTER TAV" },
	{ 0x005df, /* ן     */ "HEBREW LETTER FINAL NUN" },
	{ 0x005da, /* ך     */ "HEBREW LETTER FINAL KAF" },
	{ 0x005dd, /* ם     */ "HEBREW LETTER FINAL MEM" },
	{ 0x005e3, /* ף     */ "HEBREW LETTER FINAL PE" },
	{ 0x005e5, /* ץ     */ "HEBREW LETTER FINAL TSADI" },
	{ 0x000a7, /* §     */ "SECTION SIGN" },
	{ 0x02227, /* ∧     */ "LOGICAL AND" },
	{ 0x0221e, /* ∞     */ "INFINITY" },
	{ 0x003b1, /* α     */ "GREEK SMALL LETTER ALPHA" },
	{ 0x003b2, /* ß     */ "GREEK SMALL LETTER BETA" },
	{ 0x00393, /* Γ     */ "GREEK CAPITAL LETTER GAMMA" },
	{ 0x003c0, /* π     */ "GREEK SMALL LETTER PI" },
	{ 0x003a3, /* Σ     */ "GREEK CAPITAL LETTER SIGMA" },
	{ 0x003c3, /* σ     */ "GREEK SMALL LETTER SIGMA" },
	{ 0x000b5, /* µ     */ "MICRO SIGN" },
	{ 0x003c4, /* τ     */ "GREEK SMALL LETTER TAU" },
	{ 0x003a6, /* Φ     */ "GREEK CAPITAL LETTER PHI" },
	{ 0x00398, /* Θ     */ "GREEK CAPITAL LETTER THETA" },
	{ 0x003a9, /* Ω     */ "GREEK CAPITAL LETTER OMEGA" },
	{ 0x003b4, /* δ     */ "GREEK SMALL LETTER DELTA" },
	{ 0x0222e, /* ∮     */ "CONTOUR INTEGRAL" },
	{ 0x003c6, /* φ     */ "GREEK SMALL LETTER PHI" },
	{ 0x02208, /* ∈     */ "ELEMENT OF" },
	{ 0x02229, /* ∩     */ "INTERSECTION" },
	{ 0x02261, /* ≡     */ "IDENTICAL TO" },
	{ 0x000b1, /* ±     */ "PLUS-MINUS SIGN" },
	{ 0x02265, /* ≥     */ "GREATER-THAN OR EQUAL TO" },
	{ 0x02264, /* ≤     */ "LESS-THAN OR EQUAL TO" },
	{ 0x02320, /* ⌠     */ "TOP HALF INTEGRAL" },
	{ 0x02321, /* ⌡     */ "BOTTOM HALF INTEGRAL" },
	{ 0x000f7, /* ÷     */ "DIVISION SIGN" },
	{ 0x02248, /* ≈     */ "ALMOST EQUAL TO" },
	{ 0x000b0, /* °     */ "DEGREE SIGN" },
	{ 0x02219, /* ∙     */ "BULLET OPERATOR" },
	{ 0x000b7, /* ·     */ "MIDDLE DOT" },
	{ 0x0221a, /* √     */ "SQUARE ROOT" },
	{ 0x0207f, /* ⁿ     */ "SUPERSCRIPT LATIN SMALL LETTER N" },
	{ 0x000b2, /* ²     */ "SUPERSCRIPT TWO" },
	{ 0x000b3, /* ³     */ "SUPERSCRIPT THREE" },
	{ 0x000af, /* ¯     */ "MACRON" }
};

unicode_t charset_atari_st_to_utf32(uint8_t c, void *arg)
{
	return atari_st_charset[c].code;
}

uint8_t utf32_to_charset_atari_st(unicode_t u, void *arg)
{
	for (int c = 0; c < ARRAY_SIZE(atari_st_charset); c++)
		if (u == atari_st_charset[c].code)
			return c;

	return '?';
}

bool utf8_valid_in_atari_st(const uint8_t *u, size_t length)
{
	return utf8_valid_in_charset_string(u, length,
			charset_atari_st_to_utf32,
			utf32_to_charset_atari_st, NULL);
}
