# SPDX-License-Identifier: GPL-2.0

INTERNAL_SRC =								\
	lib/internal/file.c						\
	lib/internal/memory.c						\
	lib/internal/print.c						\
	lib/internal/string.c

INTERNAL_OBJ = $(INTERNAL_SRC:%.c=%.o)

ALL_OBJ += $(INTERNAL_OBJ)
